name: Lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
    - name: Install dependencies
      run: |
        yarn install --frozen-lockfile
    - name: Lint files
      run: |
        yarn lint
