name: Tests

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [8.x, 12.x, 13.x]
        os: 
        - ubuntu-latest
        - windows-latest
        - macos-latest


    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependancies
      run: |
        npm i
      env:
        CI: true
    - name: Build Typescript
      run: |
        npm run build --if-present
    - name: Run Tests
      run: |
        npm test
